### PR TITLE
Fix critical issues & update the Guide

### PR DESCRIPTION
**Pull request by imajus**
Fix the guide styling and actualize the links

### CODE REVIEW

**Comment by imajus** [comment]
Added more commits:
 - Fix using `const` instead of `let` in multiple places (includes #9)
 - Fix improper use of `default` helper for `disabled` attributes

**Comment by imajus** [comment]
@denihs kindly merge this one
@dr-dimitru has approved it

**Comment by pfafman** [comment]
Knock Knock.  This really needs to get merged.....

**Review by denihs — APPROVED** [review]

**Comment by denihs** [comment]
Hi, I just published the new version!

`useraccounts:core`@1.17.2

**Pull request merged**
